hideManual: true
watch:
  directories:
    - src
    - tests
  fileMask: '*.php'
notifications:
  passingTests: true
  failingTests: true
phpunit:
  binaryPath: vendor/bin/phpunit
  arguments: '--stop-on-failure  --colors=always'
  timeout: 180